name: Create Release from Changelog

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Extract changelog entry
        id: changelog
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "Extracting changelog for version $VERSION"
          
          # Extract lines between ## [VERSION] and next ## (or end of file)
          awk "/^## \\[${VERSION//./\\.}\\]/ {flag=1; next} /^## / {flag=0} flag" CHANGELOG.md > body.md
          
          echo "BODY<<EOF" >> $GITHUB_ENV
          cat body.md >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: ${{ env.BODY }}
