name: Release & Publish

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/project/cheatos

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install build tools and dev requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Build distributions
        run: python -m build

      - name: Check distributions with twine
        run: twine check dist/*

      - name: Extract changelog for this version
        id: changelog
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          awk "/^## \\[${VERSION//./\\.}\\]/ {flag=1; next} /^## / {flag=0} flag" CHANGELOG.md > body.md
          echo "BODY<<EOF" >> $GITHUB_ENV
          cat body.md >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: ${{ env.BODY }}
          files: dist/*

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
